/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aprendaefaca.gerenciamentobancario.telas;

/**
 *
 * @author Rubens
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FMenu
     */
    public TelaPrincipal() {
        super("Tela de Menu");
         initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlIMG = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCliente = new javax.swing.JMenu();
        jmCadCliente = new javax.swing.JMenuItem();
        jmAlteracaoCliente = new javax.swing.JMenuItem();
        jmConsultaCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmExcluirCliente = new javax.swing.JMenuItem();
        jmFornecedor = new javax.swing.JMenu();
        jmUsuario = new javax.swing.JMenu();
        jmCadastroUsuario = new javax.swing.JMenuItem();
        jmConsultaUsuario = new javax.swing.JMenuItem();
        jmFechar = new javax.swing.JMenu();
        jmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(TelaPrincipal.class);
        jlIMG.setIcon(resourceMap.getIcon("jlIMG.icon")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addComponent(jlIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlIMG, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        jmCliente.setText("Cliente");
        jmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClienteActionPerformed(evt);
            }
        });

        jmCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmCadCliente.setText("Cadastro Cliente");
        jmCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadClienteActionPerformed(evt);
            }
        });
        jmCliente.add(jmCadCliente);

        jmAlteracaoCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jmAlteracaoCliente.setText("Alteração Cliente");
        jmAlteracaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlteracaoClienteActionPerformed(evt);
            }
        });
        jmCliente.add(jmAlteracaoCliente);

        jmConsultaCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmConsultaCliente.setText("Consulta Cliente");
        jmCliente.add(jmConsultaCliente);
        jmCliente.add(jSeparator1);

        jmExcluirCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmExcluirCliente.setText("Excluir Cliente");
        jmCliente.add(jmExcluirCliente);

        jMenuBar1.add(jmCliente);

        jmFornecedor.setText("Fornecedor");
        jMenuBar1.add(jmFornecedor);

        jmUsuario.setText("Usuario");

        jmCadastroUsuario.setText("Cadastro Usuario");
        jmCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroUsuarioActionPerformed(evt);
            }
        });
        jmUsuario.add(jmCadastroUsuario);

        jmConsultaUsuario.setText("Consulta Usuario");
        jmConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaUsuarioActionPerformed(evt);
            }
        });
        jmUsuario.add(jmConsultaUsuario);

        jMenuBar1.add(jmUsuario);

        jmFechar.setText("Fechar");
        jmFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFecharActionPerformed(evt);
            }
        });

        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jmFechar.add(jmSair);

        jMenuBar1.add(jmFechar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadClienteActionPerformed
                    // TODO add your handling code here:
        TelaCadastroCliente cliente = new TelaCadastroCliente(this,true);
        cliente.setVisible(true);
      // System.exit(0);
    }//GEN-LAST:event_jmCadClienteActionPerformed

    private void jmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroCliente cliente = new TelaCadastroCliente(this,true);
        cliente.setVisible(true);
    }//GEN-LAST:event_jmClienteActionPerformed

    private void jmFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFecharActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jmFecharActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmAlteracaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlteracaoClienteActionPerformed
        // TODO add your handling code here:
       TelaAlteracaoCliente alteracao = new TelaAlteracaoCliente(this,true);
       alteracao.setVisible(true);
    }//GEN-LAST:event_jmAlteracaoClienteActionPerformed

    private void jmCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroUsuarioActionPerformed
       TelaCadastroUsuario cadUsr = new TelaCadastroUsuario(this,true);
       cadUsr.setLocationRelativeTo(this);
       cadUsr.setVisible(true);
    }//GEN-LAST:event_jmCadastroUsuarioActionPerformed

    private void jmConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaUsuarioActionPerformed
       TelaConsultaUsuario conUsr = new TelaConsultaUsuario(this,true);
       conUsr.setLocationRelativeTo(this);
       conUsr.setVisible(true);
    }//GEN-LAST:event_jmConsultaUsuarioActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel jlIMG;
    private javax.swing.JMenuItem jmAlteracaoCliente;
    private javax.swing.JMenuItem jmCadCliente;
    private javax.swing.JMenuItem jmCadastroUsuario;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenuItem jmConsultaCliente;
    private javax.swing.JMenuItem jmConsultaUsuario;
    private javax.swing.JMenuItem jmExcluirCliente;
    private javax.swing.JMenu jmFechar;
    private javax.swing.JMenu jmFornecedor;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JMenu jmUsuario;
    // End of variables declaration//GEN-END:variables
}
