-- CRIAR O BANCO - IN�CIO
CREATE DATABASE db_sgfapm;

USE db_sgfapm;

CREATE TABLE TB_ALUNOS(
RA_ALUNO INT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DATA_NASCIMENTO VARCHAR(50),
IDADE INT,
SEXO VARCHAR(10),
CURSO VARCHAR(50) NOT NULL,
PERIODO VARCHAR(50) NOT NULL,
MODULO VARCHAR(10) NOT NULL,
RUA VARCHAR(100),
NUMERO VARCHAR(10),
COMPLEMENTO VARCHAR(50),
CEP VARCHAR(20),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(10),
TELEFONE VARCHAR(20),
CELULAR VARCHAR(20),
E_MAIL VARCHAR(50) NOT NULL,
ATIVO BIT
);

CREATE TABLE TB_FUNCIONARIOS(
ID_FUNC INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
CARGO VARCHAR(30) NOT NULL,
SALARIO DECIMAL(10,2) NOT NULL,
DATA_ADMISSAO VARCHAR(15) NOT NULL,
DATA_DEMISSAO VARCHAR(15),
CPF VARCHAR(20) NOT NULL UNIQUE,
RG VARCHAR(20) NOT NULL UNIQUE,
TELEFONE VARCHAR(20),
CELULAR VARCHAR(20),
E_MAIL VARCHAR(50),
RUA VARCHAR(100) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
COMPLEMENTO VARCHAR(50),
CEP VARCHAR(20),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(10)
);

CREATE TABLE TB_USUARIOS(
ID_USER INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
USUARIO VARCHAR(50) NOT NULL UNIQUE,
SENHA VARCHAR(50) NOT NULL,
PERFIL VARCHAR(50) NOT NULL
);

CREATE TABLE TB_CONTRIBUICOES(
ID_CONTRIB INT PRIMARY KEY AUTO_INCREMENT,
DATA TIMESTAMP,
VALOR DECIMAL(10,2) NOT NULL,
FORMA_PAGAMENTO	VARCHAR(50) NOT NULL,
OBSERVACOES VARCHAR(255),
RA_ALUNO INT NOT NULL,
FOREIGN KEY(RA_ALUNO) REFERENCES TB_ALUNOS(RA_ALUNO)
);

CREATE TABLE TB_PRODUTOS(
ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
VALOR DECIMAL(10,2) NOT NULL,
DESCRICAO VARCHAR(255)
);

CREATE TABLE TB_VENDAS(
ID_VENDA INT PRIMARY KEY AUTO_INCREMENT,
VALOR DECIMAL(10,2) NOT NULL,
DATA TIMESTAMP NOT NULL,
FORMA_PAGAMENTO VARCHAR(50) NOT NULL,
PARCELAS VARCHAR(10) NOT NULL
);

CREATE TABLE TB_DESPESAS(
ID_DESPESAS INT PRIMARY KEY AUTO_INCREMENT,
TIPO VARCHAR(20) NOT NULL,
VALOR DECIMAL(10,2) NOT NULL,
DATA TIMESTAMP,
DESCRICAO VARCHAR(255)
);

CREATE TABLE TB_ITENS(
QUANTIDADE INT NOT NULL,
ID_PRODUTO INT NOT NULL,
ID_VENDA INT NOT NULL,
FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTOS(ID_PRODUTO),
FOREIGN KEY(ID_VENDA) REFERENCES TB_VENDAS(ID_VENDA)
);

CREATE TABLE TB_CAIXA(
ID_CAIXA INT PRIMARY KEY AUTO_INCREMENT,
DATA TIMESTAMP,
SALDO DECIMAL(10,2),
MOVIMENTO DECIMAL(10,2),
TIPO VARCHAR(50),
DESCRICAO VARCHAR(255)
);

-- Inserts de teste
-- ALUNOS
INSERT INTO TB_ALUNOS(RA_ALUNO, NOME, DATA_NASCIMENTO, IDADE, SEXO, CURSO, PERIODO, MODULO, TELEFONE, E_MAIL, ATIVO)
VALUES(11110, 'José Figueredo', '06/06/1996', 20, 'M', 'Informática', 'Noite', '3º', '3333-3333', 'josef@gmeil.com.br', 1);

INSERT INTO TB_ALUNOS(RA_ALUNO, NOME, DATA_NASCIMENTO, IDADE, SEXO, CURSO, PERIODO, MODULO, TELEFONE, E_MAIL, ATIVO)
VALUES(11111, 'Ana Lisa Dados', '04/04/1994', 22, 'F', 'Administração', 'Manhã', '1º', '4444-4444', 'analize@hotimeil.com', 1);

-- FUNCIONARIOS
INSERT INTO TB_FUNCIONARIOS (NOME, CARGO, SALARIO, DATA_ADMISSAO, CPF, RG, E_MAIL, RUA, NUMERO, CEP, BAIRRO, CIDADE, ESTADO) 
VALUES('Wellington Cidade', 'Coordenador', 50000.00, '11/01/1950', '123.456.789-01', '12.345.678-9', 'well@megahair.com', 'rua', 'numero', '01234-567', 'bairro', 'cidade', 'SP');

INSERT INTO TB_FUNCIONARIOS (NOME, CARGO, SALARIO, DATA_ADMISSAO, CPF, RG, E_MAIL, RUA, NUMERO, CEP, BAIRRO, CIDADE, ESTADO) 
VALUES('João Augusto', 'Atendente', 1000.00, '11/11/2016', '234.345.678-90', '01.234.567-8', 'johnstar@uau.com', 'rua', 'numero', '01234-567', 'bairro', 'cidade', 'SP');

-- USUARIOS
INSERT INTO TB_USUARIOS (NOME, USUARIO, SENHA, PERFIL) 
VALUES ('Administrador', 'admin', 'admin', 'admin');

INSERT INTO TB_USUARIOS (NOME, USUARIO, SENHA, PERFIL) 
VALUES ('Usuário comum', 'user', '123', 'user');

INSERT INTO TB_USUARIOS (NOME, USUARIO, SENHA, PERFIL) 
VALUES ('Wellington Cidade', 'well', '123456', 'admin');

INSERT INTO TB_USUARIOS (NOME, USUARIO, SENHA, PERFIL) 
VALUES ('João Augusto', 'joao', '123', 'user');

-- PRODUTOS
INSERT INTO TB_PRODUTOS(NOME, VALOR, DESCRICAO)
VALUES ('Camiseta', 20.00, 'Camiseta do uniforme do BG');

INSERT INTO TB_PRODUTOS(NOME, VALOR, DESCRICAO)
VALUES ('Jaleco', 40.00, 'Jaleco de Mecânica');

INSERT INTO TB_PRODUTOS(NOME, VALOR, DESCRICAO)
VALUES ('Carteirinha', 20.00, 'Carteirinha de identificação do BG');

INSERT INTO TB_PRODUTOS(NOME, VALOR, DESCRICAO)
VALUES ('Óculos', 10.00, 'Óculos de proteção para oficina de mecânica');

-- CAIXA
INSERT INTO TB_CAIXA(SALDO, DATA, MOVIMENTO, TIPO, DESCRICAO) VALUES (0.00, CURRENT_TIMESTAMP, 0.0, 'Início', 'Abertura do caixa');


-- CRIAR O BANCO - FIM
