package br.org.laramara.usse.telas;

import br.org.laramara.usse.controladores.ControladorTelaAcessoRapido;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;

/**
 *
 * @author l
 */
public class AcessoRapido extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUsuario
     */
    public AcessoRapido() {
        initComponents();
    }

    public AcessoRapido(JFrame telaPrincipal, JDesktopPane desktop) {
        this();
        controlador = new ControladorTelaAcessoRapido(telaPrincipal, desktop,lblConsultar, 
                jbtOrdemServico,jbtAgendaContato,jbtCadastrarUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblConsultar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtOrdemServico = new javax.swing.JButton();
        jbtAgendaContato = new javax.swing.JButton();
        jbtFolderCPD = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtCadastrarUsuario = new javax.swing.JButton();
        jbtCadastrarServidores = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setIconifiable(true);
        setTitle("Acesso Rápido");
        setPreferredSize(new java.awt.Dimension(640, 480));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 150));

        lblConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/laramara/usse/icones/consulta.png"))); // NOI18N
        lblConsultar.setToolTipText("Consultar");
        lblConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblConsultar.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel10.setText("Consultar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acesso"));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 150));

        jbtOrdemServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/laramara/usse/icones/acesso/icone-suporte.png"))); // NOI18N
        jbtOrdemServico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtOrdemServico.setLabel("Ordem Serviço");
        jbtOrdemServico.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtOrdemServico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOrdemServicoActionPerformed(evt);
            }
        });

        jbtAgendaContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/laramara/usse/icones/acesso/agenda-contato.png"))); // NOI18N
        jbtAgendaContato.setText("Agenda Contato");
        jbtAgendaContato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtAgendaContato.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtAgendaContato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAgendaContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAgendaContatoActionPerformed(evt);
            }
        });

        jbtFolderCPD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/laramara/usse/icones/acesso/folder-icon.png"))); // NOI18N
        jbtFolderCPD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtFolderCPD.setLabel("Pasta - CPD");
        jbtFolderCPD.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtFolderCPD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtFolderCPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFolderCPDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jbtOrdemServico)
                .addGap(18, 18, 18)
                .addComponent(jbtAgendaContato)
                .addGap(18, 18, 18)
                .addComponent(jbtFolderCPD)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtOrdemServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtAgendaContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtFolderCPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar"));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 150));
        jPanel3.setName(""); // NOI18N

        jbtCadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/laramara/usse/icones/acesso/icone-users.png"))); // NOI18N
        jbtCadastrarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jbtCadastrarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtCadastrarUsuario.setLabel("Cadastrar Usuario");
        jbtCadastrarUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtCadastrarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastrarUsuarioActionPerformed(evt);
            }
        });

        jbtCadastrarServidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/laramara/usse/icones/acesso/server-icon.png"))); // NOI18N
        jbtCadastrarServidores.setText("Cadastrar Servidores");
        jbtCadastrarServidores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtCadastrarServidores.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtCadastrarServidores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtCadastrarServidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastrarServidoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jbtCadastrarUsuario)
                .addGap(18, 18, 18)
                .addComponent(jbtCadastrarServidores, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtCadastrarServidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCadastrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        setBounds(0, 0, 868, 647);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOrdemServicoActionPerformed
       
    }//GEN-LAST:event_jbtOrdemServicoActionPerformed

    private void jbtAgendaContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAgendaContatoActionPerformed
        
    }//GEN-LAST:event_jbtAgendaContatoActionPerformed

    private void jbtFolderCPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFolderCPDActionPerformed
       
    }//GEN-LAST:event_jbtFolderCPDActionPerformed

    private void jbtCadastrarServidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastrarServidoresActionPerformed
       
    }//GEN-LAST:event_jbtCadastrarServidoresActionPerformed

    private void jbtCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastrarUsuarioActionPerformed
       
    }//GEN-LAST:event_jbtCadastrarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtAgendaContato;
    private javax.swing.JButton jbtCadastrarServidores;
    private javax.swing.JButton jbtCadastrarUsuario;
    private javax.swing.JButton jbtFolderCPD;
    private javax.swing.JButton jbtOrdemServico;
    private javax.swing.JLabel lblConsultar;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaAcessoRapido controlador;
}
