/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  m7
 * Created: Dec 15, 2016
 */

/* Drop Tables */
DROP TABLE IF EXISTS TB_FUNCIONARIOS;
DROP TABLE IF EXISTS TB_ALUNOS;
DROP TABLE IF EXISTS TB_USUARIOS;
DROP TABLE IF EXISTS TB_CONTRIBUICOES;
DROP TABLE IF EXISTS TB_PRODUTOS;
DROP TABLE IF EXISTS TB_VENDAS;
DROP TABLE IF EXISTS TB_DESPESAS;
DROP TABLE IF EXISTS TB_ITENS;
DROP TABLE IF EXISTS TB_CAIXA;

/* Create Tables */

CREATE TABLE TB_ALUNOS(
ID_ALUNOS BIGSERIAL NOT NULL,
RA_ALUNO INT NOT NULL,
NOME VARCHAR(50) NOT NULL,
DATA_NASCIMENTO VARCHAR(50),
IDADE INT,
SEXO VARCHAR(10),
CURSO VARCHAR(50) NOT NULL,
PERIODO VARCHAR(50) NOT NULL,
MODULO VARCHAR(10) NOT NULL,
RUA VARCHAR(100),
NUMERO VARCHAR(10),
COMPLEMENTO VARCHAR(50),
CEP VARCHAR(20),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(10),
TELEFONE VARCHAR(20),
CELULAR VARCHAR(20),
E_MAIL VARCHAR(50) NOT NULL,
ATIVO BIT,
CONSTRAINT tb_ALUNOS_pkey PRIMARY KEY (RA_ALUNO)
) WITHOUT OIDS;


CREATE TABLE TB_FUNCIONARIOS(
ID_FUNC BIGSERIAL NOT NULL,
NOME VARCHAR(100) NOT NULL,
CARGO VARCHAR(30) NOT NULL,
SALARIO DECIMAL(10,2) NOT NULL,
DATA_ADMISSAO VARCHAR(15) NOT NULL,
DATA_DEMISSAO VARCHAR(15),
CPF VARCHAR(20) NOT NULL UNIQUE,
RG VARCHAR(20) NOT NULL UNIQUE,
TELEFONE VARCHAR(20),
CELULAR VARCHAR(20),
E_MAIL VARCHAR(50),
RUA VARCHAR(100) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
COMPLEMENTO VARCHAR(50),
CEP VARCHAR(20),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(10),
PRIMARY KEY (ID_FUNC)
) WITHOUT OIDS;



CREATE TABLE TB_USUARIOS(
ID_USER BIGSERIAL NOT NULL,
NOME VARCHAR(50) NOT NULL,
USUARIO VARCHAR(50) NOT NULL UNIQUE,
SENHA VARCHAR(50) NOT NULL,
PERFIL VARCHAR(50) NOT NULL,
PRIMARY KEY (ID_USER)
) WITHOUT OIDS;

CREATE TABLE TB_CONTRIBUICOES(
ID_CONTRIB BIGSERIAL NOT NULL,
DATA TIMESTAMP,
VALOR DECIMAL(10,2) NOT NULL,
FORMA_PAGAMENTO	VARCHAR(50) NOT NULL,
OBSERVACOES VARCHAR(255),
RA_ALUNO INT NOT NULL REFERENCES TB_ALUNOS(RA_ALUNO),
PRIMARY KEY (ID_CONTRIB)
) WITHOUT OIDS;



CREATE TABLE TB_PRODUTOS(
ID_PRODUTO BIGSERIAL NOT NULL,
NOME VARCHAR(50) NOT NULL,
VALOR DECIMAL(10,2) NOT NULL,
DESCRICAO VARCHAR(255),
PRIMARY KEY (ID_PRODUTO)
) WITHOUT OIDS;


CREATE TABLE TB_VENDAS(
ID_VENDA BIGSERIAL NOT NULL,
VALOR DECIMAL(10,2) NOT NULL,
DATA TIMESTAMP NOT NULL,
FORMA_PAGAMENTO VARCHAR(50) NOT NULL,
PARCELAS VARCHAR(10) NOT NULL,
PRIMARY KEY (ID_VENDA)
) WITHOUT OIDS;

CREATE TABLE TB_DESPESAS(
ID_DESPESAS BIGSERIAL NOT NULL,
TIPO VARCHAR(20) NOT NULL,
VALOR DECIMAL(10,2) NOT NULL,
DATA TIMESTAMP,
DESCRICAO VARCHAR(255),
PRIMARY KEY (ID_DESPESAS)
) WITHOUT OIDS;

CREATE TABLE TB_ITENS(
ID_ITENS BIGSERIAL NOT NULL,
QUANTIDADE INT NOT NULL,
ID_PRODUTO INT NOT NULL REFERENCES TB_PRODUTOS(ID_PRODUTO),
ID_VENDA INT NOT NULL REFERENCES TB_VENDAS(ID_VENDA),
PRIMARY KEY (ID_ITENS)
) WITHOUT OIDS;


CREATE TABLE TB_CAIXA(
ID_CAIXA BIGSERIAL NOT NULL,
DATA TIMESTAMP,
SALDO DECIMAL(10,2),
MOVIMENTO DECIMAL(10,2),
TIPO VARCHAR(50),
DESCRICAO VARCHAR(255),
PRIMARY KEY (ID_CAIXA)
) WITHOUT OIDS;
