/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.org.laramara.usse.telas;

/**
 *
 * @author 5448
 */
public class TelaCadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnDadosCliente = new javax.swing.JPanel();
        jbuSalvar = new javax.swing.JButton();
        jbuCancelar = new javax.swing.JButton();
        jlaCpf = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JTextField();
        jlaRG = new javax.swing.JLabel();
        jtfRg = new javax.swing.JTextField();
        jlaSexo = new javax.swing.JLabel();
        jcoSexo = new javax.swing.JComboBox<>();
        jtfNomeCliente = new javax.swing.JTextField();
        jlaNome = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Tela Cadatro de Cliente");

        jpnDadosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        jbuSalvar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/laramara/usse/icones/Salvar.png"))); // NOI18N
        jbuSalvar.setText("Salvar");
        jbuSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jbuCancelar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/laramara/usse/icones/Cancelar.png"))); // NOI18N
        jbuCancelar.setText("Cancelar");
        jbuCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jlaCpf.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaCpf.setText("CPF:");

        jlaRG.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaRG.setText("RG:");

        jlaSexo.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaSexo.setText("Sexo:");

        jcoSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));

        jlaNome.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaNome.setText("Nome:");

        javax.swing.GroupLayout jpnDadosClienteLayout = new javax.swing.GroupLayout(jpnDadosCliente);
        jpnDadosCliente.setLayout(jpnDadosClienteLayout);
        jpnDadosClienteLayout.setHorizontalGroup(
            jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDadosClienteLayout.createSequentialGroup()
                .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDadosClienteLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlaNome)
                            .addComponent(jlaCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnDadosClienteLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jbuSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDadosClienteLayout.createSequentialGroup()
                        .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlaRG, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnDadosClienteLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jbuCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDadosClienteLayout.setVerticalGroup(
            jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDadosClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlaNome)))
                .addGap(28, 28, 28)
                .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlaCpf))
                    .addComponent(jtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jpnDadosClienteLayout.createSequentialGroup()
                .addGroup(jpnDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDadosClienteLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jlaRG))
                    .addGroup(jpnDadosClienteLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jlaSexo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jpnDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbuCancelar;
    private javax.swing.JButton jbuSalvar;
    private javax.swing.JComboBox<String> jcoSexo;
    private javax.swing.JLabel jlaCpf;
    private javax.swing.JLabel jlaNome;
    private javax.swing.JLabel jlaRG;
    private javax.swing.JLabel jlaSexo;
    private javax.swing.JPanel jpnDadosCliente;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfNomeCliente;
    private javax.swing.JTextField jtfRg;
    // End of variables declaration//GEN-END:variables
}
