/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.carloskafka.sishibernateclient.telas;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;

import org.jdesktop.application.SingleFrameApplication;

import br.com.carloskafka.sishibernateclient.controladores.ControladorTelaEditarCliente;
import br.com.carloskafka.sishibernatecommons.dtos.cliente.ClienteDTO;

/**
 *
 * @author Carlos
 */
public class TelaCliente extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6254817993027765887L;
	/**
	 * Creates new form Tela
	 */
	public TelaCliente(SingleFrameApplication app, ClienteDTO clienteDto) {
		super();
		getFrames()[0].addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent we) {
				controladorTelaCliente.fechar();
			}
		});
		getFrames()[0].setExtendedState(JFrame.MAXIMIZED_BOTH);
		initComponents();
		controladorTelaCliente = new ControladorTelaEditarCliente(this, jtfNome,
				jtfCnpj, jtfRazaoSocial, jtfEmail, jtfTelefone, clienteDto);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel5 = new javax.swing.JLabel();
		jtfSalvar = new javax.swing.JButton();
		jtfNome = new javax.swing.JTextField();
		jtfFechar = new javax.swing.JButton();
		jtfCnpj = new javax.swing.JTextField();
		jtfRazaoSocial = new javax.swing.JTextField();
		jtfEmail = new javax.swing.JTextField();
		jtfTelefone = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel5.setText("Telefone");

		jtfSalvar.setText("Salvar");
		jtfSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jtfSalvarActionPerformed(evt);
			}
		});

		jtfFechar.setText("Fechar");
		jtfFechar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jtfFecharActionPerformed(evt);
			}
		});

		jLabel1.setText("Nome");

		jLabel2.setText("CNPJ");

		jLabel3.setText("Razao Social");

		jLabel4.setText("Email");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(34, 34, 34)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jtfNome,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		206,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel2)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jtfCnpj,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		206,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
																.addGroup(
																		layout.createSequentialGroup()
																				.addComponent(
																						jtfSalvar)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jtfFechar))
																.addGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		layout.createSequentialGroup()
																				.addComponent(
																						jLabel5)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jtfTelefone))
																.addGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		layout.createSequentialGroup()
																				.addComponent(
																						jLabel3)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jtfRazaoSocial))
																.addGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		layout.createSequentialGroup()
																				.addComponent(
																						jLabel4)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jtfEmail,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						206,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addContainerGap(129, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(46, 46, 46)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfNome,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfCnpj,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfRazaoSocial,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfEmail,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jtfTelefone,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										40, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jtfSalvar)
												.addComponent(jtfFechar))
								.addGap(26, 26, 26)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jtfSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfSalvarActionPerformed
		controladorTelaCliente.salvar();
	}// GEN-LAST:event_jtfSalvarActionPerformed

	private void jtfFecharActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfFecharActionPerformed
		controladorTelaCliente.fechar();
	}// GEN-LAST:event_jtfFecharActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField jtfCnpj;
	private javax.swing.JTextField jtfEmail;
	private javax.swing.JButton jtfFechar;
	private javax.swing.JTextField jtfNome;
	private javax.swing.JTextField jtfRazaoSocial;
	private javax.swing.JButton jtfSalvar;
	private javax.swing.JTextField jtfTelefone;
	// End of variables declaration//GEN-END:variables
	private ControladorTelaEditarCliente controladorTelaCliente;
}
