/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author rubens.leme
 */
public class TelaServidores extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaServidores
     */
    public TelaServidores() {
        initComponents();
         controlador =  new ControladorAcessoRapido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtADDServidor = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Servidores");

        jbtADDServidor.setText("ADD Servidor");
        jbtADDServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtADDServidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jbtADDServidor)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jbtADDServidor)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtADDServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtADDServidorActionPerformed
       controlador.abrirTelaADDServidores();
    }//GEN-LAST:event_jbtADDServidorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtADDServidor;
    // End of variables declaration//GEN-END:variables
ControladorAcessoRapido controlador ;
}
