
/* Drop Tables */

DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS LOG;




/* Create Tables */

CREATE TABLE CLIENTE
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100),
	CNPJ VARCHAR(13),
	RAZAO_SOCIAL VARCHAR(300),
	EMAIL VARCHAR(300),
	TELEFONE VARCHAR(10),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE LOG
(
	USUARIO VARCHAR(100) NOT NULL,
	DATA TIMESTAMP NOT NULL,
	LOGGER VARCHAR(100) NOT NULL,
	NIVEL VARCHAR(50) NOT NULL,
	MENSAGEM VARCHAR(20000) NOT NULL,
	PRIMARY KEY (DATA)
) WITHOUT OIDS;



