/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.bg;

/**
 *
 * @author ruben
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    Conexao con ;
    public TelaMenu() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
       con = new Conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCadastroCliente = new javax.swing.JMenuItem();
        jmCadastroAutor = new javax.swing.JMenuItem();
        jmCadastroLivro = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmAjuda = new javax.swing.JMenu();
        jmTesteConexao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Menu");
        setResizable(false);

        jMenu1.setText("Cadastro");

        jmCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_CadastrarCliente.png"))); // NOI18N
        jmCadastroCliente.setText("Cliente");
        jmCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadastroCliente);

        jmCadastroAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_CadastrarAutor.png"))); // NOI18N
        jmCadastroAutor.setText("Autor");
        jMenu1.add(jmCadastroAutor);

        jmCadastroLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_CadastrarLivro.png"))); // NOI18N
        jmCadastroLivro.setText("Livro");
        jmCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroLivroActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadastroLivro);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_CadastrarEditora.png"))); // NOI18N
        jMenuItem4.setText("Editora");
        jMenu1.add(jMenuItem4);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bt_CadastrarCategoria.png"))); // NOI18N
        jMenuItem1.setText("Categoria");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jmAjuda.setText("Ajuda");
        jmAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAjudaActionPerformed(evt);
            }
        });

        jmTesteConexao.setText("Teste Conexão");
        jmTesteConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTesteConexaoActionPerformed(evt);
            }
        });
        jmAjuda.add(jmTesteConexao);

        jMenuBar1.add(jmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroClienteActionPerformed
        TelaCadastroCliente telaCadastroCliente = new TelaCadastroCliente();
        telaCadastroCliente.setVisible(true);
    }//GEN-LAST:event_jmCadastroClienteActionPerformed

    private void jmAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAjudaActionPerformed
       
    }//GEN-LAST:event_jmAjudaActionPerformed

    private void jmTesteConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTesteConexaoActionPerformed
       if (con.obterConexaoProjLivrariaDigital()!= null){
           Mensagem.exibirMensagem("Conectado com sucesso!");
       }else{
            Mensagem.exibirMensagem("Não Conectado!");
       }
    }//GEN-LAST:event_jmTesteConexaoActionPerformed

    private void jmCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroLivroActionPerformed
       TelaCadastroLivro telaLivro = new TelaCadastroLivro();
       telaLivro.setVisible(true);
    }//GEN-LAST:event_jmCadastroLivroActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenuItem jmCadastroAutor;
    private javax.swing.JMenuItem jmCadastroCliente;
    private javax.swing.JMenuItem jmCadastroLivro;
    private javax.swing.JMenuItem jmTesteConexao;
    // End of variables declaration//GEN-END:variables
}
