/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apf.javabd.telas;

/**
 *
 * @author Carlos
 */
public class TelaMenu extends javax.swing.JDialog {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbCadastroFornecedores = new javax.swing.JButton();
        jbCadastroCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbConsultaCliente = new javax.swing.JButton();
        jbConsultaFornecedores = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbConsultaCliente1 = new javax.swing.JButton();
        jbConsultaFornecedores1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbConsultaCliente2 = new javax.swing.JButton();
        jbConsultaFornecedores2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");
        setModal(true);
        setResizable(false);

        jbCadastroFornecedores.setText("Fornecedores");
        jbCadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroFornecedoresActionPerformed(evt);
            }
        });

        jbCadastroCliente.setText("Clientes");
        jbCadastroCliente.setMaximumSize(new java.awt.Dimension(99, 23));
        jbCadastroCliente.setMinimumSize(new java.awt.Dimension(99, 23));
        jbCadastroCliente.setPreferredSize(new java.awt.Dimension(99, 23));
        jbCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Cadastro");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Consulta");

        jbConsultaCliente.setText("Clientes");
        jbConsultaCliente.setMaximumSize(new java.awt.Dimension(99, 23));
        jbConsultaCliente.setMinimumSize(new java.awt.Dimension(99, 23));
        jbConsultaCliente.setPreferredSize(new java.awt.Dimension(99, 23));
        jbConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaClienteActionPerformed(evt);
            }
        });

        jbConsultaFornecedores.setText("Fornecedores");
        jbConsultaFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaFornecedoresActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Exclusao");

        jbConsultaCliente1.setText("Clientes");
        jbConsultaCliente1.setMaximumSize(new java.awt.Dimension(99, 23));
        jbConsultaCliente1.setMinimumSize(new java.awt.Dimension(99, 23));
        jbConsultaCliente1.setPreferredSize(new java.awt.Dimension(99, 23));
        jbConsultaCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaCliente1ActionPerformed(evt);
            }
        });

        jbConsultaFornecedores1.setText("Fornecedores");
        jbConsultaFornecedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaFornecedores1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Alteracao");

        jbConsultaCliente2.setText("Clientes");
        jbConsultaCliente2.setMaximumSize(new java.awt.Dimension(99, 23));
        jbConsultaCliente2.setMinimumSize(new java.awt.Dimension(99, 23));
        jbConsultaCliente2.setPreferredSize(new java.awt.Dimension(99, 23));
        jbConsultaCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaCliente2ActionPerformed(evt);
            }
        });

        jbConsultaFornecedores2.setText("Fornecedores");
        jbConsultaFornecedores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaFornecedores2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jbConsultaFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jbCadastroFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbConsultaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jbConsultaFornecedores1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbConsultaCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jbConsultaFornecedores2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastroFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConsultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultaFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConsultaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultaFornecedores1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConsultaCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultaFornecedores2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroClienteActionPerformed
        new TelaCliente().setVisible(true);
    }//GEN-LAST:event_jbCadastroClienteActionPerformed

    private void jbCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroFornecedoresActionPerformed
        new TelaFornecedor().show();
    }//GEN-LAST:event_jbCadastroFornecedoresActionPerformed

    private void jbConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaClienteActionPerformed
        new TelaConsultaCliente().show();

    }//GEN-LAST:event_jbConsultaClienteActionPerformed

    private void jbConsultaFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaFornecedoresActionPerformed
        new TelaConsultaFornecedor().show();
    }//GEN-LAST:event_jbConsultaFornecedoresActionPerformed

    private void jbConsultaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaCliente1ActionPerformed
        new TelaExclusaoCliente().show();
    }//GEN-LAST:event_jbConsultaCliente1ActionPerformed

    private void jbConsultaFornecedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaFornecedores1ActionPerformed
        new TelaExclusaoFornecedor().show();
    }//GEN-LAST:event_jbConsultaFornecedores1ActionPerformed

    private void jbConsultaCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaCliente2ActionPerformed
        new TelaAlteracaoCliente().show();
    }//GEN-LAST:event_jbConsultaCliente2ActionPerformed

    private void jbConsultaFornecedores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaFornecedores2ActionPerformed
        new TelaAlteracaoFornecedor().show();
    }//GEN-LAST:event_jbConsultaFornecedores2ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbCadastroCliente;
    private javax.swing.JButton jbCadastroFornecedores;
    private javax.swing.JButton jbConsultaCliente;
    private javax.swing.JButton jbConsultaCliente1;
    private javax.swing.JButton jbConsultaCliente2;
    private javax.swing.JButton jbConsultaFornecedores;
    private javax.swing.JButton jbConsultaFornecedores1;
    private javax.swing.JButton jbConsultaFornecedores2;
    // End of variables declaration//GEN-END:variables
}
