CREATE DATABASE DBPEDIDO;

USE DBPEDIDO;

CREATE TABLE PAGAMENTO(
CODIGO_ID_PAG INT NOT NULL IDENTITY,
DESCRICAO_PAG VARCHAR(20),
PRIMARY KEY (CODIGO_ID_PAG));

CREATE TABLE ESTADO(
UF_ID_EST CHAR(2) NOT NULL,
DESCRICAO_EST VARCHAR(30),
PRIMARY KEY (UF_ID_EST));

CREATE TABLE MARCA(
CODIGO_ID_MAR INT NOT NULL IDENTITY,
DESCRICAO_MAR VARCHAR(20),
PRIMARY KEY (CODIGO_ID_MAR));

CREATE TABLE CLIENTE(
CODIGO_ID_CLI INT NOT NULL IDENTITY,
NOME_CLI VARCHAR(60),
ENDERECO_CLI VARCHAR(50),
COMPLEMENTO_CLI VARCHAR(20),
BAIRRO_CLI VARCHAR(20),
CIDADE_CLI VARCHAR(40),
UF_ID_EST CHAR(2),
CEP_CLI VARCHAR(8),
RG_CLI VARCHAR(15),
DTNASCIMENTO_CLI DATETIME,
PRIMARY KEY (CODIGO_ID_CLI),
FOREIGN KEY (UF_ID_EST) 
REFERENCES ESTADO);

CREATE TABLE PRODUTO(
CODIGO_ID_PROD INT NOT NULL IDENTITY,
DESCRICAO_PROD VARCHAR(40),
VALOR_PROD NUMERIC(10,2),
UNIDADE_PROD CHAR(2),
CODIGO_ID_MAR INT,
PRIMARY KEY (CODIGO_ID_PROD),
FOREIGN KEY (CODIGO_ID_MAR)
REFERENCES MARCA);

CREATE TABLE PEDIDO(
NUMERO_ID_PED INT NOT NULL IDENTITY,
DATA_PED DATETIME,
CODIGO_ID_CLI INT,
CODIGO_ID_PAG INT,
SUBTOTAL_PED NUMERIC(10,2),
DESCONTO_PED NUMERIC(10,2),
TOTAL_PED NUMERIC(10,2),
PRIMARY KEY (NUMERO_ID_PED),
FOREIGN (CODIGO_ID_CLI)REFERENCES CLIENTE,
FOREIGN (CODIGO_ID_PAG)REFERENCES PAGAMENTO);

CREATE TABLE ITEMPEDIDO(
NUMERO_ID_PED INT NOT NULL,
CODIGO_ID_PROD INT NOT NULL,
QUANTIDADE_ITEM NUMERIC(5,2),
TOTAL_ITEM NUMERIC(10,2),
PRIMARY KEY(NUMERO_ID_PED, CODIGO_ID_PROD),
FOREIGN KEY (NUMERI_ID_PED) REFERENCES PEDIDO,
FOREIGN KEY (CODIGO_ID_PROD) REFERENCES PRODUTO);




select * from ESTADO;