-- MySQL Script generated by MySQL Workbench
-- Thu Dec  6 14:53:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_exemplo_ejb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_exemplo_ejb` ;
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema bd_exemplo_ejb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_exemplo_ejb` DEFAULT CHARACTER SET utf8 ;
USE `bd_exemplo_ejb` ;

-- -----------------------------------------------------
-- Table `bd_exemplo_ejb`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_exemplo_ejb`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `bd_exemplo_ejb`.`Pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
