/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bg.sisprojeto.telas;

import java.awt.BorderLayout;

/**
 *
 * @author Rubens
 */
public class TelaMenu2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu2
     */
    public TelaMenu2() {
        initComponents();
      setExtendedState(MAXIMIZED_BOTH);
        setLayout(new BorderLayout());
        add(jlaImagemFundo, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlaImagemFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCadastroCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmCadastroFornecedor = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmAlterarCliente = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmAlterarFornecedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmConsultarCliente = new javax.swing.JMenuItem();
        jmConsultarFornecedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Menu");
        setResizable(false);

        jlaImagemFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlaImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/carloskafka/sisprojeto/logo-BG.png"))); // NOI18N

        jMenu1.setText("Cadatros");

        jmCadastroCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/carloskafka/sisprojeto/icones/ico-cliente.png"))); // NOI18N
        jmCadastroCliente.setMnemonic('c');
        jmCadastroCliente.setText("Cadastro Cliente");
        jmCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadastroCliente);
        jMenu1.add(jSeparator1);

        jmCadastroFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmCadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/carloskafka/sisprojeto/icones/ico-fornecedor.png"))); // NOI18N
        jmCadastroFornecedor.setText("Cadastro Fornecedor");
        jmCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadastroFornecedor);
        jMenu1.add(jSeparator3);

        jmAlterarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/carloskafka/sisprojeto/icones/ico-alterar-cliente.png"))); // NOI18N
        jmAlterarCliente.setText("Alterar Cliente");
        jmAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlterarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmAlterarCliente);
        jMenu1.add(jSeparator4);

        jmAlterarFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmAlterarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/carloskafka/sisprojeto/icones/ico-alterar-fornecedor.png"))); // NOI18N
        jmAlterarFornecedor.setText("Alterar Fornedor");
        jmAlterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlterarFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmAlterarFornecedor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jmConsultarCliente.setText("Consultar Cliente");
        jmConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jmConsultarCliente);

        jmConsultarFornecedor.setText("Consultar Fornecedor");
        jmConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarFornecedorActionPerformed(evt);
            }
        });
        jMenu2.add(jmConsultarFornecedor);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlaImagemFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jlaImagemFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroClienteActionPerformed
        new TelaCadastroCliente().show();
    }//GEN-LAST:event_jmCadastroClienteActionPerformed

    private void jmCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroFornecedorActionPerformed
        new TelaFornecedor().show();
    }//GEN-LAST:event_jmCadastroFornecedorActionPerformed

    private void jmAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlterarClienteActionPerformed
        new TelaAlteracaoCliente().show();
    }//GEN-LAST:event_jmAlterarClienteActionPerformed

    private void jmAlterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlterarFornecedorActionPerformed
        new TelaAlteracaoFornecedor().show();
    }//GEN-LAST:event_jmAlterarFornecedorActionPerformed

    private void jmConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarClienteActionPerformed
        new TelaConsultaCliente().show();
    }//GEN-LAST:event_jmConsultarClienteActionPerformed

    private void jmConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarFornecedorActionPerformed
        new TelaConsultaFornecedor().show();
    }//GEN-LAST:event_jmConsultarFornecedorActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel jlaImagemFundo;
    private javax.swing.JMenuItem jmAlterarCliente;
    private javax.swing.JMenuItem jmAlterarFornecedor;
    private javax.swing.JMenuItem jmCadastroCliente;
    private javax.swing.JMenuItem jmCadastroFornecedor;
    private javax.swing.JMenuItem jmConsultarCliente;
    private javax.swing.JMenuItem jmConsultarFornecedor;
    // End of variables declaration//GEN-END:variables
}
